<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HATI-SDG00096" failures="1" tests="2" name="ADTTest.Modify_Existing_Patient_Admission_Request_2" time="33.635" errors="0" timestamp="2023-12-05T19:00:36 IST" skipped="0">
  <testcase classname="ADTTest.Modify_Existing_Patient_Admission_Request_2" name="TC_01_verify_That_User_Is_Able_To_Login_ADT_Dashboard_Screen" time="10.239"/>
  <system-out/>
  <testcase classname="ADTTest.Modify_Existing_Patient_Admission_Request_2" name="TC_02_Verfiy_That_User_Is_Able_To_Modify_Existing_Patient_Admission_Request" time="23.396">
    <failure message="Assertion pass patient able to select the id expected [Passport] but found [Primaery Identification]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Assertion pass patient able to select the id expected [Passport] but found [Primaery Identification]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at ADTpages.Modify_Existing_Patient_Admission_Request_1.Modify_Existing_Patient_Admission_Requestfunc(Modify_Existing_Patient_Admission_Request_1.java:82)
at ADTTest.Modify_Existing_Patient_Admission_Request_2.TC_02_Verfiy_That_User_Is_Able_To_Modify_Existing_Patient_Admission_Request(Modify_Existing_Patient_Admission_Request_2.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1207)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_02_Verfiy_That_User_Is_Able_To_Modify_Existing_Patient_Admission_Request -->
  <system-out/>
</testsuite> <!-- ADTTest.Modify_Existing_Patient_Admission_Request_2 -->
